export { default as ProjectWorkspace } from './ProjectWorkspace'
export { default as ProjectBreadcrumb } from './ProjectBreadcrumb'
export { default as ProjectSubTabs, PROJECT_WORKSPACE_TABS } from './ProjectSubTabs'
export { default as ProjectOnboardingEmptyState } from './ProjectOnboardingEmptyState'
export { default as SetupProjectModal } from './SetupProjectModal'
export { default as ResourcesTab } from './resources/ResourcesTab'
export { default as TasksTab } from './tasks/TasksTab'
export { default as KanbanTab } from './kanban/KanbanTab'
export { default as CalendarTab } from './calender/CalendarTab'
// export { default as CreateTaskModal } from './CreateTaskModal'
// export { default as DeleteTaskModal } from './DeleteTaskModal'
