import { jsPDF, GState } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import {
  buildStatusItems,
  buildAllocationItems,
  buildTrend,
  buildUpcoming,
  computeLifecycleProgress,
  getCurrentStageName,
  getProjectResources,
  getProjectTasks,
  resolveTaskAssignee,
  formatDate,
  formatTaskStatus,
} from "./analytics";

const toTaskList = (tasks) => (Array.isArray(tasks) ? tasks : []);

const buildAnalytics = (project, tasks) => {
  const taskList = toTaskList(tasks);
  const resources = getProjectResources(project);

  return {
    resources,
    statusItems: buildStatusItems(taskList),
    allocationItems: buildAllocationItems(taskList),
    trend: buildTrend(taskList),
    upcoming: buildUpcoming(taskList),
    summary: [
      { label: "Project Name", value: project?.projectName ?? "—" },
      { label: "Project ID", value: project?.projectId ?? "—" },
      { label: "Current Stage", value: getCurrentStageName(project) || "—" },
      { label: "Lifecycle Progress", value: `${computeLifecycleProgress(project)}%` },
      { label: "Total Tasks", value: taskList.length },
      { label: "Total Resources", value: resources.length },
    ],
  };
};

const buildProjectDetails = (project) => {
  const pm = project?.projectManager;
  const pmValue = pm?.fullName ? `${pm.fullName} (${pm.email})` : pm?.email ?? "—";

  return [
    { label: "Client", value: project?.clientName ?? "—" },
    { label: "Type", value: project?.productType ?? "—" },
    { label: "Product", value: project?.productName ?? "—" },
    { label: "Location", value: project?.location ?? "—" },
    { label: "Sitecode", value: project?.siteCode ?? "—" },
    { label: "AMC", value: project?.amcPercentage ?? "—" },
    { label: "Register For", value: "—" },
    { label: "Purchase Order Date", value: formatDate(project?.purchaseOrderDate) },
    { label: "Expected Commencement Date", value: formatDate(project?.commencementDate) },
    { label: "Assigned Project Manager", value: pmValue },
  ];
};

const buildAllTasks = (project, tasks) => {
  const resources = getProjectResources(project);

  return getProjectTasks(project, toTaskList(tasks)).map((task) => ({
    title: task?.title,
    assigneeName: resolveTaskAssignee(task, resources),
    beginDate: formatDate(task?.startDate),
    dueDate: formatDate(task?.dueDate),
    status: formatTaskStatus(task?.status),
    priority: task?.priority ?? "",
  }));
};

const RESOURCE_COLUMNS = [
  { label: "First Name", value: (row) => row?.firstName ?? "" },
  { label: "Last Name", value: (row) => row?.lastName ?? "" },
  { label: "Staff ID", value: (row) => row?.staffId ?? "" },
  { label: "Designation", value: (row) => row?.designation ?? "" },
  { label: "Phone", value: (row) => row?.phoneNumber ?? "" },
  { label: "Email", value: (row) => row?.email ?? "" },
];

const STATUS_COLUMNS = [
  { label: "Status", value: (row) => row.label },
  { label: "Task Count", value: (row) => row.count },
  { label: "Percentage", value: (row) => `${row.percent}%` },
];

const ALLOCATION_COLUMNS = [
  { label: "Resource", value: (row) => row.label },
  { label: "Task Count", value: (row) => row.count },
  { label: "Percentage", value: (row) => `${row.percent}%` },
];

const SUMMARY_COLUMNS = [
  { label: "Metric", value: (row) => row.label },
  { label: "Value", value: (row) => row.value },
];

const TASK_COLUMNS = [
  { label: "Task", value: (row) => row.title ?? "" },
  { label: "Assignee", value: (row) => row.assigneeName },
  { label: "Begin Date", value: (row) => row.beginDate },
  { label: "Due Date", value: (row) => row.dueDate },
  { label: "Status", value: (row) => row.status },
  { label: "Priority", value: (row) => row.priority },
];

const trendRows = (trend) =>
  trend.months.map((month, index) => ({
    month: month.label,
    created: trend.created[index],
    completed: trend.completed[index],
  }));

const TREND_COLUMNS = [
  { label: "Month", value: (row) => row.month },
  { label: "Created", value: (row) => row.created },
  { label: "Completed", value: (row) => row.completed },
];

const UPCOMING_COLUMNS = [
  { label: "Task", value: (row) => row.task },
  { label: "Due Date", value: (row) => row.dueDate },
  { label: "Reminder", value: (row) => row.reminder },
];

const slugify = (value) => String(value ?? "project").replace(/[^a-z0-9]+/gi, "-").toLowerCase();

const buildStamp = (user) =>
  `Generated by ${user?.fullName ?? "—"} (${user?.email ?? "—"}) on ${new Date().toLocaleDateString("en-GB")}`;

export const exportAnalyticsPdf = ({ project, tasks, user }) => {
  const { resources, statusItems, allocationItems, trend, upcoming } =
    buildAnalytics(project, tasks);
  const projectDetails = buildProjectDetails(project);
  const allTasks = buildAllTasks(project, tasks);

  const doc = new jsPDF({ orientation: "landscape" });
  const pageWidth = doc.internal.pageSize.getWidth();

  const drawWatermark = () => {
    doc.setGState(new GState({ opacity: 0.08 }));
    doc.setFontSize(36);
    doc.setTextColor(27, 60, 74);
    doc.text(buildStamp(user), pageWidth / 2, doc.internal.pageSize.getHeight() / 2, {
      angle: 30,
      align: "center",
    });
    doc.setGState(new GState({ opacity: 1 }));
  };

  doc.setFontSize(16);
  doc.setTextColor(27, 60, 74);
  doc.text(project?.projectName ?? "Project Analytics", 14, 14);

  doc.setFontSize(9);
  doc.setTextColor(99, 99, 99);
  doc.text(`Project ID: ${project?.projectId ?? "—"}`, 14, 21);
  doc.text(`Exported: ${new Date().toLocaleDateString("en-GB")}`, pageWidth - 14, 21, {
    align: "right",
  });

  let cursorY = 30;

  const addTable = (title, columns, rows) => {
    doc.setFontSize(12);
    doc.setTextColor(27, 60, 74);
    doc.text(title, 14, cursorY);

    autoTable(doc, {
      head: [columns.map((column) => column.label)],
      body: rows.map((row) => columns.map((column) => column.value(row))),
      startY: cursorY + 4,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 60, 74], textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [247, 249, 251] },
      margin: { top: 14, left: 14, right: 14, bottom: 14 },
      didDrawPage: () => drawWatermark(),
    });

    cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 14;
  };

  addTable("Project Details", SUMMARY_COLUMNS, projectDetails);
  addTable("All Tasks", TASK_COLUMNS, allTasks);
  addTable("Task Status Overview", STATUS_COLUMNS, statusItems);
  addTable("Task Completion Trend (Last 6 Months)", TREND_COLUMNS, trendRows(trend));
  addTable("Upcoming Tasks", UPCOMING_COLUMNS, upcoming);
  addTable("Task Allocation by Resource", ALLOCATION_COLUMNS, allocationItems);
  addTable("Project Resources", RESOURCE_COLUMNS, resources);

  doc.save(`${slugify(project?.projectId)}-analytics.pdf`);
};

const sheetFromRows = (columns, rows) => {
  const data = [
    columns.map((column) => column.label),
    ...rows.map((row) => columns.map((column) => column.value(row))),
  ];
  const worksheet = XLSX.utils.aoa_to_sheet(data);
  worksheet["!cols"] = columns.map(() => ({ wch: 24 }));
  return worksheet;
};

export const exportAnalyticsExcel = ({ project, tasks, user }) => {
  const { resources, statusItems, allocationItems, trend, upcoming } =
    buildAnalytics(project, tasks);
  const projectDetails = buildProjectDetails(project);
  const allTasks = buildAllTasks(project, tasks);

  const workbook = XLSX.utils.book_new();
  const append = (sheetName, columns, rows) => {
    XLSX.utils.book_append_sheet(workbook, sheetFromRows(columns, rows), sheetName);
  };

  append(
    "Report Info",
    SUMMARY_COLUMNS,
    [
      { label: "Generated By", value: user?.fullName ?? "—" },
      { label: "Email", value: user?.email ?? "—" },
      { label: "Generated At", value: new Date().toLocaleString("en-GB") },
      { label: "Project", value: project?.projectName ?? "—" },
      { label: "Project ID", value: project?.projectId ?? "—" },
    ],
  );
  append("Project Details", SUMMARY_COLUMNS, projectDetails);
  append("All Tasks", TASK_COLUMNS, allTasks);
  append("Task Status", STATUS_COLUMNS, statusItems);
  append("Completion Trend", TREND_COLUMNS, trendRows(trend));
  append("Upcoming Tasks", UPCOMING_COLUMNS, upcoming);
  append("Resource Allocation", ALLOCATION_COLUMNS, allocationItems);
  append("Resources", RESOURCE_COLUMNS, resources);

  XLSX.writeFile(workbook, `${slugify(project?.projectId)}-analytics.xlsx`, {
    compression: true,
  });
};

export const exportProjectAnalytics = (format, payload) => {
  switch (format) {
    case "pdf":
      return exportAnalyticsPdf(payload);
    case "excel":
      return exportAnalyticsExcel(payload);
    default:
      throw new Error(`Unsupported analytics export format: ${format}`);
  }
};
